### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by autonia** [open-rpa/node-red-contrib-tagui#6]
I was using this module successfully earlier in the year, but when I tried to use it today, it gave me this error:

```
Unable to open file: /Users/david/robot.tag.js

  phantomjs://code/bootstrap.js:113 in __die
```

Sorry if this is unhelpful. I'm somewhat of a novice at Node Red.

**Comment by skadefro** [comment]
phantomjs ... i need to read up on that at some point .. 
So for now, I think we need some guidance from @kensoh

**Comment by kensoh** [comment]
Hi @skadefro thanks for pinging me, thanks @autonia for reporting this!

Can I check if you are using Mac? and have upgraded to Monterey version?

I'm seeing early reports of this issue due to the new Mac version removing PHP - https://www.techgenyz.com/2021/06/18/macos-12-monterey-update-built-in-php/

Solution for now is to install PHP manually, until this can be automated (I don't think so need password to run homebrew) or co-packaged. Below will install Homebrew package manager for macOS and then install PHP which TagUI requires to run.
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install php
```
If you are using Mac and Monterey version or later, try the above to see if that works.

<blockquote><img src="https://www.techgenyz.com/wp-content/uploads/2021/06/macos-monterey.jpg" width="48" align="right"><div><img src="https://www.techgenyz.com/wp-content/uploads/2019/07/cropped-favicon-192x192.png" height="14"> TechGenyz</div><div><strong><a href="https://www.techgenyz.com/2021/06/18/macos-12-monterey-update-built-in-php/">macOS 12 Monterey update will no longer have built-in PHP</a></strong></div><div>Almost a week ago Apple had announced the update to its desktop operating system- macOS 12 Monterey. The new update offers several new features, some of</div></blockquote>

**Comment by autonia** [comment]
I am in fact on Monterey, but I also got the same error on an instance in IBM Cloud.

**Comment by kensoh** [comment]
With above observations so far, it could still be related to PHP missing. Some Linux OS does not ship with PHP, for example Ubuntu, and would require an additional step to install PHP to run the TagUI module for Node-RED.

PHP is used to convert the human language .tag files into working JavaScript code to drive the automation behind TagUI.

**Comment by autonia** [comment]
I installed PHP on my Mac using your instructions and that solved the error! I'll see if I can figure out how to install it on IBM Cloud tomorrow. Thanks very much for your help!

**Comment by kensoh** [comment]
Sure no probs! Do ping back here if you run into any blockers.

I don't have a good solution for this Mac issue (because PHP installation can't simply be automated without user keying in password), but I will look out for more data points on what can be done to minimise user friction for this Mac OS change.

**Comment by autonia** [comment]
I'm back. This time I'm on a Windows machine, and I'm getting the "php is missing" error in the tagui node-red module. I've installed PHP via XAMPP, but no luck. @kensoh, do you have any pointers for how to make sure the module is able to access PHP?

**Comment by skadefro** [comment]
Oh, there is a bug in my code. 
ill push an update in a sec

**Comment by skadefro** [comment]
done, it can take up to an hour before the nodered catalog gets updated

**Comment by autonia** [comment]
Thanks! Appreciate it.

**Comment by kensoh** [comment]
Thanks @skadefro! time flies, i'll be heading to London this weekend and @ruthtxh will be taking over TagUI project. I'll still continue to maintain the RPA for Python project in my own time. Thanks @autonia for raising this!

**Comment by skadefro** [comment]
@kensoh Glad to hear you made it all work out regarding london. Hope you have a smooth transition. And sorry to see your leaving the TagUI project, but also happy it can continue in the hands of @ruthtxh . 
@autonia let us know, if the issue is solved for you now.

**Comment by autonia** [comment]
Yes, this is resolved. Thanks all for your help.
